/**
 * Created by Administrator on 2017/6/27 0027.
 */
export const UPDATE_SONGSRC = 'UPDATE_SONGSRC'
export const UPDATE_PLAYINGSONGID = 'UPDATE_PLAYINGSONGID'
export const UPDATE_PLAYINGSONGIMG = 'UPDATE_PLAYINGSONGIMG'
export const UPDATE_PLAYINGSONGNAME = 'UPDATE_PLAYINGSONGNAME'
export const UPDATE_ISPLAYING = 'UPDATE_ISPLAYING'
export const UPDATE_STARTTIME = 'UPDATE_STARTTIME'
export const UPDATE_TOTALTIME = 'UPDATE_TOTALTIME'
export const UPDATE_SONGLIST = 'UPDATE_SONGLIST'
export const UPDATE_CURRENTSONGLISTINDEX = 'UPDATE_CURRENTSONGLISTINDEX'